# Generated by Django 3.2.5 on 2021-08-31 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cusotem',
            new_name='customer',
        ),
    ]
