# Generated by Django 3.2.5 on 2021-08-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_cusotem_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
